stages:
  prepare_datasets:
    cmd: python -m src.prepare_datasets
    deps:
      - ./src/load_datasets.py
      - ./src/prepare_datasets.py
      - data
    params:
      - input.train_part
      - input.years
    outs:
      - preprocessed
  train:
    cmd: python -m src.train
    deps:
    - ./src/model.py
    - ./src/train.py
    - preprocessed
    params:
    - input.batch_size
    - input.train_part
    - input.years
    - train.buffer_size
    - train.epochs
    outs:
    - ./saved_models/main.h5
    metrics:
    - ./metrics/training.csv:
        cache: false
  test:
    cmd: python -m src.test
    deps:
    - preprocessed
    - saved_models/main.h5
    - src/test.py
    params:
    - input.batch_size
    metrics:
    - metrics/test.json:
        cache: false
