
input:
    batch_size: 128 # Allow parallel training, but bigger batch may overfit
    train_part: 0.8 # Training dataset procent, test dataset will be 20%
    years: 4 # count of years of dataset which take for training and testing, start from last

train:
    epochs: 100
    features: 4
    patience: 2
    input_width: 30 # Count of input time series
    label_width: 30 # Count of output/labeled time series
    label_shift: 1  # Shift between input and labeled windows
    label_columns:
        - 'Close'