
input:
    batch_size: 128 # Allow parallel training, but bigger batch may overfit
    train_part: 0.8 # Training dataset procent, test dataset will be 20%
    years: 4 # count of years of dataset which take for training and testing, start from last

train:
    epochs: 20
    label_steps: 30 # Steps count on which in future will be generation of labels
    features: 4